spring.application.name=sistema-inventario-back
spring.datasource.url=jdbc:postgresql://ep-falling-moon-acsltrxy-pooler.sa-east-1.aws.neon.tech:5432/db-sastreria
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vPZjd6fLW7sH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true